book:
    title:            "Dynacase 3.2 Tutorial"
    author:           "Anakeen Labs &lt;labs@anakeen.com&gt;"
    edition:          "1.0"
    language:         fr
    publication_date: ~

    generator: { name: easybook, version: 4.4 }

    contents:
        # available content types: acknowledgement, afterword, appendix, author,
        # chapter, conclusion, cover, dedication, edition, epilogue, foreword,
        # glossary, introduction, license, lof (list of figures), lot (list of
        # tables), part, preface, prologue, title, toc (table of contents)
        - { element: cover }
        - { element: edition }
        - { element: license, content: license.md }
        - { element: author, content: author.md }
        - { element: toc   }
        - { element: glossary }
        - { element: chapter, number:  1, content: preamble.md }
        - { element: chapter, number:  2, content: specification.md }
        - { element: chapter, number:  3, content: starting-up.md }
        - { element: chapter, number:  4, content: groups-roles.md }
        - { element: chapter, number:  5, content: the-beginning.md }
        - { element: chapter, number:  6, content: family-creation.md }
        - { element: chapter, number:  7, content: family-inheritance.md }
        - { element: chapter, number:  8, content: family-first-customisation.md }
        - { element: chapter, number:  9, content: family-advanced-customisation.md}
        - { element: chapter, number:  10, content: app-action.md }
        - { element: chapter, number:  11, content: permissions.md }
        - { element: chapter, number:  12, content: workflow-beginning.md }
        - { element: chapter, number:  13, content: workflow-paramters.md}
        - { element: chapter, number:  14, content: representation.md}
        - { element: chapter, number:  15, content: representation-HTML-ODT.md }
        - { element: chapter, number:  16, content: translations.md }
        - { element: chapter, number:  17, content: deployment.md }
        - { element: lof   }
        - { element: lot   }

    editions:

        web:
            format:         html
            highlight_code: true
            include_styles: true
            labels:         []
            theme:          anakeen
            toc:
                deep:       3
                elements:   ["figure", "table"]

        website:
            extends:        web
            format:         html_chunked
            highlight_code: true

        ebook:
            format:         epub
            highlight_code: false
            include_styles: true
            labels:         ['appendix', 'chapter']
            toc:
                deep:       1
                elements:   ["appendix", "chapter"]

        print:
            format:         pdf
            include_styles: true
            highlight_code: true
            isbn:           ~
            labels:         ['figure', 'chapter']
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outter:     20mm
            page_size:      A4
            toc:
                deep:       2
                elements:   ["chapter"]
            two_sided:      true
